apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth-service
type: Opaque
stringData:
  PORT: {{ .Values.secret.PORT | quote }}
  SECRET_KEY: {{ .Values.secret.SECRET_KEY | quote }}
  IS_DEVELOPMENT: {{ .Values.secret.IS_DEVELOPMENT | quote }}
  DATABASE_HOST: {{ .Values.secret.DATABASE_HOST | quote }}
  DATABASE_DB_NAME: {{ .Values.secret.DATABASE_DB_NAME | quote }}
  DATABASE_USER: {{ .Values.secret.DATABASE_USER | quote }}
  DATABASE_PASSWORD: {{ .Values.secret.DATABASE_PASSWORD | quote }}
  KAFKA_URL: {{ .Values.secret.KAFKA_URL | quote }}